# Assignment No 1b
###### *Hassan Raza*
----
## Goal

Your goal in this assigment is to implement and refresh the multivariate concepts learned during the previous weeks using the Python language. This will not only solidify your Python understanding but also give you strong footing for further advancement :)

**Note** Please note that can use *numpy and scipy* to complete the tasks. In case you need any help you can post on google classroom.

## Submission Instructions
You are required to submit the original notebook file on the google classroom (with .ipynb extension), with complete set of outputs. Students failing to do so will get zero marks. 

*Please read each step carefully and understand it fully before proceeding with code writing*

## Plagiarism
Any form of plagiarism will not be tolerated and result in 0 marks.

**So Lets Start**

In [93]:
# magic command to include all the necessary libraries
%pylab inline 

%pylab is deprecated, use %matplotlib inline and import the required libraries.
Populating the interactive namespace from numpy and matplotlib


C:\Users\muham\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\IPython\core\magics\pylab.py:166: UserWarning: pylab import has clobbered these variables: ['short', 'mean', 'norm', 'std', 'long']
`%matplotlib` prevents importing * from pylab and numpy
  warn("pylab import has clobbered these variables: %s"  % clobbered +


In [94]:
#Download the IRIS dataset
#"!" means run the bash (shell) command
!wget http://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data

'wget' is not recognized as an internal or external command,
operable program or batch file.


In [123]:
#import pandas and name this namespace as pd
import pandas as pd

In [124]:
#Load data and name the columns
data=pd.read_csv('iris.csv')

print (data.describe())

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000


In [125]:
data

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [126]:
#Code for generating data....
datalist=[] #create an empty list
# data list is a list of two elements, where index=0 contains data corresponding to petal 
# length and index=1 contains data corresponding to petal width
datalist.append(list(data['PetalLengthCm'].dropna()))
datalist.append(list(data['PetalWidthCm'].dropna()))
datalist.append(list(data['SepalLengthCm'].dropna()))
datalist.append(list(data['SepalWidthCm'].dropna()))

#If you want you build a numpy array from this list.

print ("PetalLength=", datalist[0])
print ("PetalWidth=", datalist[1])

#This and above code are both same...
# datalist=[0]*2#create a list of 2 elements
# datalist[0]=(list(data['PetalLength'].dropna()))
# datalist[1]=(list(data['PetalWidth'].dropna()))
#data list is a list of two elements, where index=0 contains data corresponding to petal 
# length and index=1 contains data corresponding to petal width
# print("PetalLength=", datalist[0])
# print("PetalWidth=", datalist[1])

PetalLength= [1.4, 1.4, 1.3, 1.5, 1.4, 1.7, 1.4, 1.5, 1.4, 1.5, 1.5, 1.6, 1.4, 1.1, 1.2, 1.5, 1.3, 1.4, 1.7, 1.5, 1.7, 1.5, 1.0, 1.7, 1.9, 1.6, 1.6, 1.5, 1.4, 1.6, 1.6, 1.5, 1.5, 1.4, 1.5, 1.2, 1.3, 1.5, 1.3, 1.5, 1.3, 1.3, 1.3, 1.6, 1.9, 1.4, 1.6, 1.4, 1.5, 1.4, 4.7, 4.5, 4.9, 4.0, 4.6, 4.5, 4.7, 3.3, 4.6, 3.9, 3.5, 4.2, 4.0, 4.7, 3.6, 4.4, 4.5, 4.1, 4.5, 3.9, 4.8, 4.0, 4.9, 4.7, 4.3, 4.4, 4.8, 5.0, 4.5, 3.5, 3.8, 3.7, 3.9, 5.1, 4.5, 4.5, 4.7, 4.4, 4.1, 4.0, 4.4, 4.6, 4.0, 3.3, 4.2, 4.2, 4.2, 4.3, 3.0, 4.1, 6.0, 5.1, 5.9, 5.6, 5.8, 6.6, 4.5, 6.3, 5.8, 6.1, 5.1, 5.3, 5.5, 5.0, 5.1, 5.3, 5.5, 6.7, 6.9, 5.0, 5.7, 4.9, 6.7, 4.9, 5.7, 6.0, 4.8, 4.9, 5.6, 5.8, 6.1, 6.4, 5.6, 5.1, 5.6, 6.1, 5.6, 5.5, 4.8, 5.4, 5.6, 5.1, 5.1, 5.9, 5.7, 5.2, 5.0, 5.2, 5.4, 5.1]
PetalWidth= [0.2, 0.2, 0.2, 0.2, 0.2, 0.4, 0.3, 0.2, 0.2, 0.1, 0.2, 0.2, 0.1, 0.1, 0.2, 0.4, 0.4, 0.3, 0.3, 0.3, 0.2, 0.4, 0.2, 0.5, 0.2, 0.2, 0.4, 0.2, 0.2, 0.2, 0.2, 0.4, 0.1, 0.2, 0.1, 0.2, 0.2, 0.1, 0.2, 0.2, 0.3, 0.3, 0.2, 0.6, 0.4

*In all the tasks given below use the list variable `datalist` (defined above) to answer all the questions.*

#### Task1
----------------
Lets model the petal length and width as continuous random variable $X=(x_1,x_2)$. Find the mean of this random variable. Here $x_1$ specifies the petal length and $x_2$ its width.

In [127]:
#Write your code here
import numpy as np
def calculate_mean(petal_length, petal_width):

    array1 = np.array(petal_length)
    array2 = np.array(petal_width)
    mean1 = array1.mean()
    mean2 = array2.mean()
    return mean1 , mean2
    

mean_petal_length, mean_petal_width = calculate_mean(datalist[0], datalist[1])
print(f"Mean of Petal Length (x_1): {mean_petal_length}")
print(f"Mean of Petal Width (x_2): {mean_petal_width}")


Mean of Petal Length (x_1): 3.758666666666666
Mean of Petal Width (x_2): 1.1986666666666668


#### Task2
----------------
Compute the covariance matrix $X$ using outper product formula, i.e. $\Sigma=\frac{1}{n}Z^T\;Z$, where $Z$ is centered data matrix (mean = 0)

In [128]:
import numpy as np

def covariance_matrix(data1, data2):
    array1 = np.array(data1)
    array2 = np.array(data2)
    
    mean1 = np.mean(array1)
    mean2 = np.mean(array2)

    z1 = array1 - mean1
    z2 = array2 - mean2

    Z = np.array([z1, z2])

    covariance_matrix = np.dot(Z, Z.T) / len(array1)
    
    return covariance_matrix

cov_matrix = covariance_matrix(datalist[0], datalist[1])

print(f"Covariance matrix is:\n{cov_matrix}")


Covariance matrix is:
[[3.09242489 1.28774489]
 [1.28774489 0.57853156]]


#### Task3: Multivariate Gaussian
----------------
Let's model $X$ with multivariate Gaussian. Find the probability of having flowers with petal width and height in the following range $P(3.5 < x_1 < 3.7,5.5 < x_2 <5.6)$.
Recall that 
$$f_{\mathbf x}(x_1,\ldots,x_k) = \frac{1}{\sqrt{(2\pi)^k|\boldsymbol\Sigma|}} \exp\left(-\frac{1}{2}({\mathbf x}-{\boldsymbol\mu})^\mathrm{T}{\boldsymbol\Sigma}^{-1}({\mathbf x}-{\boldsymbol\mu}) \right)$$

where ${\mathbf x}$ is a real k-dimensional column vector and $|\boldsymbol\Sigma|$ is the determinant of $\boldsymbol\Sigma$. For our this case $k=2$ 

In [129]:
#Write your code here, you are not allowed to use scipy and numpy function here... 


determinant = cov_matrix[0][0] * cov_matrix[1][1] = cov_matrix[0][1] * cov_matrix[1][0]

inverse = [[cov_matrix[1][1] / determinant , -cov_matrix[0][1] / determinant],
           [-cov_matrix[1][0] / determinant , cov_matrix[0][0] / determinant]
           ]    




def multivariate_gaussian():
    pass


multivariate_gaussian()


SyntaxError: cannot assign to expression (449910521.py, line 4)

In [103]:
#Now go and use the function to find the pdf value and compares these newly computed value
#with the earlier value and compute the difference...

#### Task4: Multivariate Gaussian

Now consider that both the attributes are statistically independent and normally distributed then what will be the probability of $P(3.5 < x_1 < 3.7,5.5 < x_2 <5.6)$


#### Task5: Categorical Random Variables.
----------------
Lets categorize the petal length variable to four categories, i.e very short $\in[1,1.6]$, short $\in(1.6,4.4]$, long $\in(4.4,5.1]$, very long $\in(5.1,6.9]$ and model this varible using random variable $x$

Find the probability of this cateogrical random variable.

In [130]:
#Write your code here
def categorical_random_prob(feature):
    n = len(feature)

    count_vs = 0
    count_s = 0
    count_l = 0
    count_vl = 0
    for i in feature:
        if i >= 1 and i <= 1.6:
            count_vs +=1
        if i >1.6 and i <= 4.4:
            count_s +=1
        if i >4.4 and i <= 5.1:
            count_l +=1
        if i >5.1 and i <= 6.9:
            count_vl +=1

    return count_vs/n , count_s/n , count_l/n , count_vl/n



very_short , short , long , very_long = categorical_random_prob(datalist[0])

print(f"Probability of very short is {very_short}")
print(f"Probability of short is {short}")
print(f"Probability of long is {long}")
print(f"Probability of very long is {very_long}")


Probability of very short is 0.29333333333333333
Probability of short is 0.23333333333333334
Probability of long is 0.24666666666666667
Probability of very long is 0.22666666666666666


#### Task6: Categorical Random Variables.
Find the mean and covariance matrix of categorical variable $x$.

In [131]:
#Write your code here
def categorize(data):
    encoding = []
    for i in data:
        if 1 <= i <= 1.6:
            encoding.append([1, 0, 0, 0])  # Very short
        elif 1.6 < i <= 4.4:
            encoding.append([0, 1, 0, 0])  # Short
        elif 4.4 < i <= 5.1:
            encoding.append([0, 0, 1, 0])  # Long
        elif 5.1 < i <= 6.9:
            encoding.append([0, 0, 0, 1])  # Very long
    return np.array(encoding)

def calculate_mean(categorical_data):
    return np.mean(categorical_data, axis=0)


def calculate_covariance(one_hot_data , mean_vector):
    centered_data = one_hot_data - mean_vector
    return np.dot(centered_data.T, centered_data) / len(one_hot_data)
   

categorical_data = categorize(datalist[0])

mean_vector = calculate_mean(categorical_data)
print(mean_vector)
covariance_matrix = calculate_covariance(categorical_data , mean_vector)
covariance_matrix

[0.29333333 0.23333333 0.24666667 0.22666667]


array([[ 0.20728889, -0.06844444, -0.07235556, -0.06648889],
       [-0.06844444,  0.17888889, -0.05755556, -0.05288889],
       [-0.07235556, -0.05755556,  0.18582222, -0.05591111],
       [-0.06648889, -0.05288889, -0.05591111,  0.17528889]])

#### Task7: Categorical Random Variables.

If we select 10 random flowers what will be the probability of picking 3 very short length, 2 short length, 4 long length and 1 very long petal length flowers.

In [132]:
def factorial(n):
    if n == 0 or n == 1:
        return 1
    else:
        return n * factorial(n - 1)
    

# Number of flowers selected from each category
k_very_short = 3
k_short = 2
k_long = 4
k_very_long = 1

# total flowers
n = 10


term1 = factorial(n) / (factorial(k_very_short) * factorial(k_short) * factorial(k_long) * factorial(k_very_long))

# Step 2: Calculate the probability for this specific selection
multivariate_prob = term1 * (pow(very_short, k_very_short) * pow(short, k_short) * pow(long, k_long) * pow(very_long, k_very_long))

# Print the result
print(f"Probability: {multivariate_prob}")


Probability: 0.014529072337116129


#### Task8: Bivariate Categorical Random Variables.
----------------
Lets also categorize the petal width variable to three categories, i.e short $\in[0.1,1.0]$, medium  $\in(1.0,1.75)$, long $\in(1.75,2.5]$.

Now lets model both the petal length and width as bivariate categorical random variable $X$.
Find the probability for following cases.

$$p(x_1=[1000], x_2=[000])$$
$$p(x_1=[1000], x_2=[001])$$

$$p(x_1=[0010], x_2=[010])$$
$$p(x_1=[0001], x_2=[100])$$


In [133]:
#Write your code here

# for petal width
        
def categorizing_PW(feature):

    PW_short = 0
    PW_long = 0
    PW_medium = 0
    n = len(feature)

    for i in feature:
        if (i>=0.1 and i<=1.0):
            PW_short+=1
        elif (i>1.0 and i<=1.75):
            PW_medium+=1
        elif (i>1.75 and i<=2.5):
            PW_long+=1


    return PW_short/n , PW_medium/n , PW_long/n


Prob_PW_short , Prob_PW_Medium , Prob_PW_long = categorizing_PW(datalist[1])

print(f"Probability of short petal width {Prob_PW_short}")
print(f"Probability of medium petal width {Prob_PW_Medium}")
print(f"Probability of long petal width {Prob_PW_long}")

Probability of short petal width 0.38
Probability of medium petal width 0.31333333333333335
Probability of long petal width 0.30666666666666664


In [134]:
# Now to model both petal length and width

# since we have already the petal length and wdth


case1 = very_short  # [1000] and [000]
case2 = very_short * Prob_PW_long # [1000] and [001]
case3 = long * Prob_PW_Medium # [0010] and [010]
case4 = very_long * Prob_PW_short #[0001] and [100]


print(f"Probability of case [1000] and [000] {case1}")
print(f"Probability of case [1000] and [001] {case2}")
print(f"Probability of case [0010] and [010] {case3}")
print(f"Probability of case [0001] and [100] {case4}")

Probability of case [1000] and [000] 0.29333333333333333
Probability of case [1000] and [001] 0.08995555555555555
Probability of case [0010] and [010] 0.0772888888888889
Probability of case [0001] and [100] 0.08613333333333333


#### Task9: Normalization
----------------
Normalize both the attributes (petal length and petal width) such that after normalization their values must lie in the interval [-2, 5]

In [135]:
#Write your code here
def StandardNormalization(feature):
    minimum = min(feature)
    maximum = max(feature)
    nparray = np.array(feature)

    # subtract from minimum
    newarray = nparray - minimum
    range1 = maximum - minimum
    # normalize value between range 0 and 1
    newarray2 = newarray / range1
    # now to normalize value between -2 and 5
    range2 = 5 - (-2)
    scaled_array = (newarray2 * range2)-2
    
    return scaled_array


PL_Normalize = StandardNormalization(datalist[0])
PW_Normalize = StandardNormalization(datalist[1])




print(f"The standard normalization of Petal length is {PL_Normalize}")
print(f"The standard normalization of Petal Width is {PW_Normalize}")

The standard normalization of Petal length is [-1.52542373 -1.52542373 -1.6440678  -1.40677966 -1.52542373 -1.16949153
 -1.52542373 -1.40677966 -1.52542373 -1.40677966 -1.40677966 -1.28813559
 -1.52542373 -1.88135593 -1.76271186 -1.40677966 -1.6440678  -1.52542373
 -1.16949153 -1.40677966 -1.16949153 -1.40677966 -2.         -1.16949153
 -0.93220339 -1.28813559 -1.28813559 -1.40677966 -1.52542373 -1.28813559
 -1.28813559 -1.40677966 -1.40677966 -1.52542373 -1.40677966 -1.76271186
 -1.6440678  -1.40677966 -1.6440678  -1.40677966 -1.6440678  -1.6440678
 -1.6440678  -1.28813559 -0.93220339 -1.52542373 -1.28813559 -1.52542373
 -1.40677966 -1.52542373  2.38983051  2.15254237  2.62711864  1.55932203
  2.27118644  2.15254237  2.38983051  0.72881356  2.27118644  1.44067797
  0.96610169  1.79661017  1.55932203  2.38983051  1.08474576  2.03389831
  2.15254237  1.6779661   2.15254237  1.44067797  2.50847458  1.55932203
  2.62711864  2.38983051  1.91525424  2.03389831  2.50847458  2.74576271
  2.15

#### Task10: Class wise mean vector and covariance matrix...
Iris dataset have three different classes, now go and compute the class-wise (setosa, versicolor and virginica) mean vector and covariance matrix.

In [136]:
import numpy as np

def classify(df):
    
    setosa = df[df['Species'] == 'Iris-setosa'].iloc[:, 1:-1].values # selects columns for features only (excluding the first column with ids and the last column with species labels).
    versicolor = df[df['Species'] == 'Iris-versicolor'].iloc[:, 1:-1].values
    virginica = df[df['Species'] == 'Iris-virginica'].iloc[:, 1:-1].values

    return setosa, versicolor, virginica


def classesmean(setosa, versicolor, virginica):
    setosa_mean = np.mean(setosa, axis=0)
    versicolor_mean = np.mean(versicolor, axis=0)
    virginica_mean = np.mean(virginica, axis=0)
    
    return setosa_mean, versicolor_mean, virginica_mean


def covariance_matrix(data):
    return np.cov(data , rowvar=False)

setosa, versicolor, virginica = classify(data)

mean_setosa, mean_versicolor, mean_virginica = classesmean(setosa, versicolor, virginica)


print(f"Mean of Setosa class: {mean_setosa}")
print(f"Mean of Versicolor class: {mean_versicolor}")
print(f"Mean of Virginica class: {mean_virginica}")

covariance_setosa = covariance_matrix(setosa)
covariance_versicolor = covariance_matrix(versicolor)
covariance_virginica = covariance_matrix(virginica)

print(f"Co-variance of setosa matrix is {covariance_setosa}")
print(f"Co-variance of versicolor matrix is {covariance_versicolor}")
print(f"Co-variance of virginica matrix is {covariance_virginica}")

Mean of Setosa class: [5.006 3.418 1.464 0.244]
Mean of Versicolor class: [5.936 2.77  4.26  1.326]
Mean of Virginica class: [6.588 2.974 5.552 2.026]
Co-variance of setosa matrix is [[0.12424898 0.10029796 0.01613878 0.01054694]
 [0.10029796 0.14517959 0.01168163 0.01143673]
 [0.01613878 0.01168163 0.03010612 0.00569796]
 [0.01054694 0.01143673 0.00569796 0.01149388]]
Co-variance of versicolor matrix is [[0.26643265 0.08518367 0.18289796 0.05577959]
 [0.08518367 0.09846939 0.08265306 0.04120408]
 [0.18289796 0.08265306 0.22081633 0.07310204]
 [0.05577959 0.04120408 0.07310204 0.03910612]]
Co-variance of virginica matrix is [[0.40434286 0.09376327 0.3032898  0.04909388]
 [0.09376327 0.10400408 0.07137959 0.04762857]
 [0.3032898  0.07137959 0.30458776 0.04882449]
 [0.04909388 0.04762857 0.04882449 0.07543265]]


#### Task11: Caclulating the Probability of a flower belonging to a particular class
Using above information, lets model each class to be modeled by continuous multivariate Gaussian Random varible. Now we have recorded a flower with following attributes (sepal lenght=4, petal length=6, sepal width=4, sepal length=5.5) in the field, which class it belongs. 

In [49]:
#Write your code here

def multivariate_gaussian_pdf(data , mean , covariance):
    length = len(data)
    cov_inv = np.linalg.inv(covariance)
    cov_det = np.linalg.det(covariance)

    exponent = -1/2(np.transpose(data-mean)) * cov_inv * (data - mean)
    denominator = 1/np.sqrt((2*3.14)**length**cov_det)
    return (1/denominator)*np.exp(exponent)

attributes = np.array([4.0 , 6.0 , 4 , 5.5])

# Calculate the probability of the flower for each class
prob_setosa = multivariate_gaussian_pdf(attributes, mean_setosa, covariance_setosa)
prob_versicolor = multivariate_gaussian_pdf(attributes, mean_versicolor, covariance_versicolor)
prob_virginica = multivariate_gaussian_pdf(attributes, mean_virginica, covariance_virginica)

<>:8: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<>:8: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
C:\Users\muham\AppData\Local\Temp\ipykernel_15452\505551434.py:8: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
  exponent = -1/2(np.transpose(data-mean)) * cov_inv * (data - mean)


LinAlgError: Singular matrix


#### Task12:  X is a normally distributed variable with mean μ = 30 and standard deviation σ = 4. Find 

a) P(x < 40)

b) P(x > 21)

c) P(30 < x < 35)

You can use scipy.stats.norm functions to answer these questions. These problems are contributed by an anonymous source.

In [137]:
#Write your code here

from scipy.stats import norm

mean = 30
std = 4


probability_a = norm.cdf(40, mean, std)
print(f"P(X < 40) = {probability_a:.4f}")

probability_b = 1 - norm.cdf(21, mean, std)
print(f"P(X > 21) = {probability_b:.4f}")

probability_c = norm.cdf(35, mean, std) - norm.cdf(30, mean, std)
print(f"P(30 < X < 35) = {probability_c:.4f}")


P(X < 40) = 0.9938
P(X > 21) = 0.9878
P(30 < X < 35) = 0.3944


#### Task13: 
The time taken to assemble a car in a certain plant is a random variable having a normal distribution with a mean of 20 hours and a standard deviation of 2 hours. What is the probability that a car can be assembled at this plant in:

a) less than 19.5 hours?

b) between 20 and 22 hours?

In [138]:
#Write your code here

mean = 20
std = 2

probability_a = norm.cdf(19.5 , 20 , 2)
print(f"Probability of Part A is {probability_a}")

probability_b = norm.cdf(22, mean, std) - norm.cdf(20, mean, std)
print(f"Probability of Part B is {probability_b}")


Probability of Part A is 0.4012936743170763
Probability of Part B is 0.3413447460685429


#### Task14:
A manufacturer of metal pistons finds that on average, 12% of his pistons are rejected because they are either oversized or undersized. What is the probability that a batch of 10 pistons will contain

(a) no more than 2 rejects?

(b) at least 2 rejects?

In [139]:
#Write your code here
from scipy.stats import binom
n = 10
prob_of_rejection = 12/100

part_a = binom.cdf(2 , n , prob_of_rejection)
print(f"Probability of part A is {part_a}")
part_b = 1 - binom.cdf(1 , n , prob_of_rejection)
print(f"Probability of part B is {part_b}")


Probability of part A is 0.8913182062780245
Probability of part B is 0.3417249657959588
